stages:
  load_data:
    cmd: python src\stage_01_load_and_save.py --config=params.yaml
    deps:
      - src/stage_01_load_and_save.py
      - src/utils/common.py
    params:
      - data_source.gdrive_source
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv

